### ISSUE TITLE
an error occur

### ISSUE THREAD

**Issue by SuperDickHead** [guyuchao/iNAS#3]
torch.nn.modules.module.ModuleAttributeError: 'iNASSupernet' object has no attribute 'module'.
This error when one epoch is trained and try to valid the supernet。I wonder if this is a bug? i use pytorch 1.7.1,seems to qualify.I am really looking forward for your help. And great work it is.

**Comment by guyuchao** [comment]
How much GPU did you use? Single GPU or Multiple GPU?

**Comment by SuperDickHead** [comment]
> How much GPU did you use? Single GPU or Multiple GPU?

I use 1 1080Ti with torch1.7.1+cu101.请问我prefetch-mode需要写cuda嘛。我还配了一个环境是python=3.8，pytorch1.7.0+cudatoolkit10.1.243,但直接运行我发现并没有开启GPU加速，我把prefetch-mode设为GPU，会一直卡在一个地方，最后一条log显示：2022-05-21 09:59:21,467 INFO: Model [OneShotModel] is created.

**Comment by guyuchao** [comment]
The problem is because you run the training in single GPU. If you run the algorithm in multiple GPU(>=2), then the .module will be added by nn.distributed.DistributedDataParallel. I will fix the single gpu training. You can leave the prefetch-mode to empty or CPU, since the memory of 1080Ti is quite small.

**Comment by SuperDickHead** [comment]
okok.I'm really looking forward to your update! This is an excellent work,i have read your paper throughly. Best wishes!
